"""empty message

Revision ID: 53772e2e47a0
Revises: 
Create Date: 2021-02-20 23:09:06.834663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53772e2e47a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('cat', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry', 'cat', ['cat'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_column('entry', 'cat')
    # ### end Alembic commands ###
